booking/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('bookTechnician/', views.bookTechnician, name='bookTechnician'),
    path('bookNow/<int:technician_id>/', views.bookNow, name='bookNow'),
    path('changeStatus/<int:booking_id>/', views.changeStatus, name='changeStatus'),
    path('giveStatus/<int:booking_id>/', views.giveStatus, name='giveStatus'),
    path('customerBookingList/',views.customerBookingList, name='customerBookingList'),
    path('checkout/<int:booking_id>/',views.checkout, name='checkout'),
    path('checkout_session/<int:booking_id>/',views.checkout_session, name='checkout_session'),
    path('pay_success/',views.pay_success, name='pay_success'),
    path('pay_cancel/',views.pay_cancel, name='pay_cancel'),

    # SEARCH
    path('search/', views.search, name='search'),


]

chat/urls.py
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.messages_page, name='messages_page'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fixit_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', views.admin, name='admin'),
    path('', views.home, name='home'),
    path('services/', views.services, name='services'),
    path('adminTechnician/', views.adminTechnician, name='adminTechnician'),
    path('adminCustomer/', views.adminCustomer, name='adminCustomer'),
    path('adminBooking/', views.adminBooking, name='adminBooking'),
    path('assignStatus/<int:technician_id>/', views.assignStatus, name='assignStatus'),
    path('deleteUser/<int:customer_id>/', views.deleteUser, name='deleteUser'),
    path('deleteTechnician/<int:technician_id>/', views.deleteTechnician, name='deleteTechnician'),
    path('deletebooking/<int:booking_id>/', views.deletebooking, name='deletebooking'),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User, UserProfile
from technician.models import Technician

class Booking(models.Model):
    CHOICES = (
        ("ACCEPT", "Accept"),
        ("REJECT", "Reject"),
        ("COMPLETED", "Completed"),
        ("PENDING", "Pending"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings')
    technician = models.ForeignKey(Technician, on_delete=models.CASCADE, related_name='bookings')
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=250, blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    booking_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=100, choices=CHOICES, default="PENDING")
    is_paid = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Populate email, name, and address fields dynamically
        self.email = self.user.email
        self.name = f"{self.user.first_name} {self.user.last_name}"
        if self.user.userprofile:
            self.address = self.user.userprofile.address
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.email} - {self.technician.user.email}"


class Payment(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE, related_name='payment')
    charge = models.IntegerField()
    time_stamp=models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.charge = self.booking.technician.service_charge
        super().save(*args, **kwargs)

    def __str__(self):
        return self.booking.email
    

accounts/forms.py
from django import forms
from .models import User, UserProfile
from django.forms.widgets import PasswordInput
from django.utils.safestring import mark_safe

class PasswordInputWithToggle(PasswordInput):
    def render(self, name, value, attrs=None, renderer=None):
        input_attrs = attrs.copy()
        input_attrs['class'] = 'form-control'
        rendered_input = super().render(name, value, input_attrs, renderer)
        toggle_button = """
        <div class="input-group-append">
            <button class="btn btn-outline-secondary toggle-password" type="button">
                <i class="fa fa-eye"></i>
            </button>
        </div>
        """
        return mark_safe(f'<div class="input-group">{rendered_input}{toggle_button}</div>')


    class Media:
        css = {
            'all': ('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css',)
        }
        js = ('https://code.jquery.com/jquery-3.6.0.min.js', '../fixit_main/static/js/custom.js')

class UserForm(forms.ModelForm):
  password = forms.CharField(widget=PasswordInputWithToggle())
  confirm_password = forms.CharField(widget=PasswordInputWithToggle())
  class Meta:
    model = User
    fields = ['first_name', 'last_name', 'profile_picture', 'username', 'email', 'phone_number', 'password',]

  def clean(self):
    cleaned_data = super(UserForm, self).clean()
    password = cleaned_data.get('password')
    confirm_password = cleaned_data.get('confirm_password')

    if password != confirm_password:
      raise forms.ValidationError(
        "Password does not match"
      )
    if not any(char.isalnum() for char in password):
        raise forms.ValidationError("Password must contain at least one alphanumeric character.")
    if len(password) < 8:
        raise forms.ValidationError("Password must be at least 8 characters long.")

    # Check if the password contains at least one alphanumeric character

class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Start typing...',
        'required': 'required',
        'class': 'form-control px-2', 
    }))
    latitude = forms.CharField(widget=forms.HiddenInput(attrs={'readonly': 'readonly', 'class': 'form-control'}))
    longitude = forms.CharField(widget=forms.HiddenInput(attrs={'readonly': 'readonly', 'class': 'form-control'}))

    class Meta:
        model = UserProfile
        fields = ['address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude',]
        widgets = {
            'country': forms.HiddenInput(attrs={'class': 'form-control'}),
            'state': forms.HiddenInput(attrs={'class': 'form-control'}),
            'city': forms.HiddenInput(attrs={'class': 'form-control'}),
            'pin_code': forms.HiddenInput(attrs={'class': 'form-control'}),
        }

booking/forms.py
from django import forms
from .models import Booking

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['email', 'name', 'address', 'phone_number']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }

booking/views.py
from datetime import date
from django.utils import timezone
from django.shortcuts import render,redirect
import stripe
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Exists, OuterRef
from accounts.models import User
from rating.models import Rating
from .forms import BookingForm 
from technician.models import Technician
from booking.models import Booking, Payment
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from accounts.views import check_role_technician, check_role_customer
from django.urls import reverse
from .utils import send_notification_to_technician, send_notification_to_user
from django.contrib.auth import login
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance
# Create your views here.
def bookTechnician(request):
    technicians = Technician.objects.all()  # Queryset for all technicians
    paginator = Paginator(technicians, 3) 

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # already_booked = any(technician.is_booked_status for technician in technicians)
    context = {
        'page_obj': page_obj, 
        # 'already_booked': already_booked, 
    }
    return render(request, 'booking/bookTechnician.html', context)



# def bookNow(request, technician_id):
#     user_profile = request.user.userprofile
#     technician = get_object_or_404(Technician, id=technician_id)
#     today_date = date.today().strftime('%Y-%m-%d')
#     current_time = timezone.now().strftime('%H:%M')
#     context = {
#         'technician': technician,
#         'user_profile': user_profile,
#         'today_date': today_date,
#         'current_time': current_time,
#     }
#     return render(request, 'booking/bookNow.html', context)

@login_required(login_url='login')
@user_passes_test(check_role_customer)
def bookNow(request, technician_id):
    user_profile = request.user.userprofile
    technician = get_object_or_404(Technician, id=technician_id)
    today_date = date.today().strftime('%Y-%m-%d')
    current_time = timezone.now().strftime('%H:%M')

      # Assign values to context dictionary
    context = {
        'user': request.user,
    }

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.technician = technician
            booking.save()

            mail_subject = 'You have been requested for booking'
            mail_template = 'accounts/emails/booking_request_email.html'

            send_notification_to_technician(technician.user.email, mail_subject, mail_template, technician.user)

            messages.success(request, 'Congratulations booking request has been sent with email notification')
            return redirect(reverse('bookNow', kwargs={'technician_id': technician_id}))

    else:
        # Filling the form with initial data
        initial_data = {
            'email': request.user.email,
            'name': f"{request.user.first_name} {request.user.last_name}",
            'address': request.user.userprofile.address,
            'phone_number': request.user.phone_number,
            'booking_date': today_date,  # Assuming today's date as default
            'booking_time': current_time  # Assuming current time as default
        }
        form = BookingForm(initial=initial_data)

    # Assign values to context dictionary
    context = {
        'form': form,
        'technician': technician,
        'user_profile': user_profile,
        'today_date': today_date,
        'current_time': current_time,
    }
    return render(request, 'booking/bookNow.html', context)


@login_required(login_url='login')
@user_passes_test(check_role_technician)
def changeStatus(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    
    context = {
        'booking': booking,
    }
    
    return render(request, 'booking/change_status.html', context)

@login_required(login_url='login')
@user_passes_test(check_role_technician)
def giveStatus(request, booking_id):
    if request.method == 'POST':
        new_status = request.POST.get('status')
        booking = get_object_or_404(Booking, pk=booking_id)
        old_status = booking.status
        booking.status = new_status
        booking.save()

        # Send notification based on the new status
        if new_status == 'ACCEPT':
            mail_subject = 'Booking Accepted'
            mail_template = 'accounts/emails/accepted_notification_email.html'
            booking.technician.is_booked_status = True
            booking.technician.save()
        elif new_status == 'REJECT':
            mail_subject = 'Booking Rejected'
            mail_template = 'accounts/emails/rejected_notification_email.html'
        elif new_status == 'COMPLETED':
            mail_subject = 'Booking Completed'
            mail_template = 'accounts/emails/completed_notification_email.html'
            booking.technician.is_booked_status = False
            booking.technician.save()
        elif new_status == 'PENDING':
            mail_subject = 'Booking Pending'
            mail_template = 'accounts/emails/pending_notification_email.html'

        # Send email notification to technician
        send_notification_to_user(booking.email, mail_subject, mail_template, booking.user)

        # Send success message to the user
        messages.success(request, f'Booking status changed to {new_status}')

        return redirect('technicianBookingList')
    context = {
        'booking': booking,
    }
    
    return render(request, 'booking/change_status.html', context)

@login_required(login_url='login')
def customerBookingList(request):
    # Get the current logged-in customer
    customer = request.user
  
    bookings = Booking.objects.filter(user=customer)
    ratings = Rating.objects.filter(user=customer)
    paginator = Paginator(bookings, 3) 

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
        
    context = {
        'bookings': bookings,
        'ratings': ratings,
        'page_obj': page_obj,
    }
    return render(request, 'customer/customerBookingList.html', context)


# @login_required(login_url='login')
# @user_passes_test(check_role_customer)
def checkout(request, booking_id):
    bookings = get_object_or_404(Booking, pk=booking_id)
    context = {
        'bookings': bookings
    }
    return render(request, 'booking/checkout.html', context)


stripe.api_key=''

# @login_required(login_url='login')
# @user_passes_test(check_role_customer)
def checkout_session(request,booking_id):
	booking=Booking.objects.get(pk=booking_id)
	session=stripe.checkout.Session.create(
		payment_method_types=['card'],
		line_items=[{
	      'price_data': {
	        'currency': 'npr',
	        'product_data': {
	          'name': booking.name,
	        },
	        'unit_amount': booking.technician.service_charge*100,
	      },
	      'quantity': 1,
	    }],
	    mode='payment',

	    success_url = f'http://127.0.0.1:8000/accounts/booking/pay_success?session_id={{CHECKOUT_SESSION_ID}}',

	    cancel_url='http://127.0.0.1:8000/accounts/booking/pay_cancel',
	    # success_url='http://127.0.0.1:8000/accounts/booking/customerBookingList',
	    # cancel_url='http://127.0.0.1:8000/accounts/booking/customerBookingList',
	    client_reference_id=booking_id
	)
	return redirect(session.url, code=303)



# @login_required(login_url='login')
# @user_passes_test(check_role_customer)
# def pay_success(request):
#     session = stripe.checkout.Session.retrieve(request.GET['session_id'])
#     booking_id = session.client_reference_id
#     booking = Booking.objects.get(pk=booking_id)
#     user = request.user
    
#     Payment.objects.create(
#         booking=booking,
#         charge=booking.technician.service_charge,

#     )
#     booking.is_paid = True
#     booking.save(update_fields=["is_paid"])
#     messages.success(request, 'Payment successfull')
#     return render(request, 'booking/success.html')
    # return redirect(request, 'customer/customerBookingList.html')


def pay_success(request):
    session_id = request.GET.get('session_id')
    if session_id:
        session = stripe.checkout.Session.retrieve(session_id)
        booking_id = session.client_reference_id
        booking = Booking.objects.get(pk=booking_id)
        Payment.objects.create(
            booking=booking,
            charge=booking.technician.service_charge,
        )
        booking.is_paid = True
        booking.save(update_fields=["is_paid"])
        messages.success(request, 'Payment successful')
        
        user = booking.user
        if user.is_authenticated:

            return redirect('customerBookingList')
        else:
            login(request, user)
            return redirect('customerBookingList')
    else:
        return redirect('cancel')

def pay_cancel(request):
	return render(request, 'booking/cancel.html')


def search(request):
    if not 'address' in request.GET:
        return redirect('bookTechnician')
    else:

        address = request.GET['address']
        latitude = request.GET['lat']
        longitude = request.GET['lng']
        radius = request.GET['radius']
        s_type = request.GET['s_type']

        page_obj = Technician.objects.filter(service_type__icontains=s_type, is_approved=True, user__is_active=True)
        if latitude and longitude and radius:
            pnt = GEOSGeometry('POINT(%s %s)' %  (longitude, latitude), 4326)
            

templates/booking/bookNow.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<style>
  input[type="text"],
    [type="date"],
    [type="time"] {
        width: 100%;
        padding: 8px;
        border: 2px solid #555454;
        border-radius: 5px;
      }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6" style="background-color: #e5f1ff; max-height: 470px; max-width: 50%;">
      <img src="{{ technician.user.profile_picture.url }}" alt="Profile Photo" class="img-fluid rounded-circle m-3" style="width: 150px; height: 150px;"> 
      <div class="mx-4 d-flex flex-row gap-3">
        <h2 class='fw-bold'>{{ technician.user.first_name }} {{ technician.user.last_name }}</h2>
        {% if technician.is_available_status == True %}
          <h6 class="fw-bold p-2 rounded text-light" style="background-color: #070441;">Available</h6>
          {% elif technician.is_available_status == False %}
          <h6 class="fw-bold p-2 rounded text-light" style="background-color: #070441;">Unavailable</h6>
          {% endif %}
      </div>
      <h5 class='mx-4 mt-3 mb-5'>{{ technician.technician_description }}</h5>
    </div>

    <div class="col-sm-5 mt-2">
      <!-- search -->
      <div>
        <form class="mx-2" style='width: 80%;'>
          <div class="input-group" style="padding: 2px;">
            <input type="text" class="form-control border border-secondary rounded" placeholder="Search...">
          </div>       
        </form>
      </div>
      <!--  -->

      <!-- Textual content  -->
      <h3 class='mx-3 mt-3 fw-bold fs-1 text-secondary'>Why will you choose me?</h3>
      <ul class='mx-3 mt-3 fw-bold fs-4 text-secondary'>
        <li class="mt-4"> Fully Satisfaction Guarantee
          & Commitment</li>
          <li class="mt-4">Trusted Professionals &
            Quality Services</li>
      </ul>

    </div>
  </div>
</div>

<h4 class='mt-5 fw-bold fs-2 text-center'>Book Now</h4>

<div class="container mt-3" style="background-color: #e5f1ff; height: 680px; width: 60%;">
  <div class="row justify-content-center">
    <h4 class='fw-bold text-center fs-3 mt-5 mb-5'>Please Fill Out The Form & <br>
      Confirm Your Booking</h4>
      
        <div style='padding-left: 18%; padding-right: 18%;'>
          <form action="" class="form-fields-set" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <ul class="">
              <li class="list-unstyled">
                <div class="row">
                  <div class="col-lg-12">
                    <ul class="list-unstyled">
                      <li class="mb-2">
                        <div class="col-md-12">
                          <div class="field-holder">
                            <label for="email" type="email">Email</label>
                            {{form.email}}
                            
                          </div>
                        </div>
                      </li>
                      <li class="mb-2">
                        <div class="col-md-12">
                          <div class="field-holder">
                            <label for="Name">Name</label>
                            {{form.name}}
                          </div>
                        </div>
                      </li>
                      <li class="mb-2">
                        <div class="col-md-12">
                          <div class="field-holder">
                            <label for="Zip code">Address</label>
                            {{form.address}}
                          </div>
                        </div>
                      </li>
                      <li class="mb-2">
                        <div class="col-md-12">
                          <div class="field-holder">
                            <label for="contact">Phone Number</label>
                            {{form.phone_number}}
                          </div>
                        </div>
                      </li>
                      <li class="row mb-2">
                        <div class="col-md-6">
                          <div class="field-holder">
                            <label for="Date">Date:</label>
                            <input type="date" name="booking_date" id="booking_date" value="{{ today_date }}" min="{{ today_date }}">
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="field-holder">
                            <label for="Time">Time</label>
                            <input type="time" name="" id="" value="{{current_time}}">
                          </div>
                        </div>
                      </li>
                    </ul>
                        <!-- Button -->
                          <div class='row justify-content-center mt-4' style='padding-left: 36%; padding-right: 36%;'>
                            <input type="submit" value="Book Now" class="btn fw-bold text-light border-0" style='background-color: #070441; padding-top: 8%; padding-bottom: 8%'>
                          </div>
                  </div>
                </div>
              </li>
            </ul>
          </form>
        </div>

  </div>
</div>

<!-- Banner -->
<div class='container-fluid p-0 mt-4' style='overflow-x: hidden; position: relative;'>
  <div class='row'>
    <img src="{% static 'images/bookbanner.jpg' %}" alt="" style='max-width: 100%; height:180px;'>
    <h3 class="position-absolute text-center top-50 fw-bold fs-1" style="color: #a22020;">Get It done quickly!</h3>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
      const bookingDateInput = document.getElementById('booking_date');
      
      
      const todayDate = new Date().toISOString().split('T')[0];
      
      
      bookingDateInput.min = todayDate;
      
      
      bookingDateInput.addEventListener('change', function() {
          const selectedDate = bookingDateInput.value;
          
          
          if (selectedDate < todayDate) {
              bookingDateInput.value = todayDate;
          }
      });
  });
</script>



{% include "includes/alerts.html" %}

	<!-- Footer -->

{% endblock  %}

templates/booking/bookTechnician.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<style>

  .card {
    padding: 40px; 
    border: none;    }
  
  .card-img-top {
    width: 170px; 
    height: auto; 
  }
  
    .pagination .page-item.active .page-link {
        background-color: #6c757d; /* Dark grey color */
        border-color: #6c757d; /* Dark grey color */
    }
  
    @keyframes show-toast {
      0% {bottom: -100%}
      20% {bottom: 100px}
      80% {bottom: 100px}
      100% {bottom: -100%}
    }
    
    .show-notification {
      position: fixed;
      bottom: 100%;
      right: 20px;
      animation-name: show-toast;
      animation-duration: 8s;
    }
</style>
<body>
<!-- Hero Section -->
<div class="container-fluid">
  <div class="row text-center" style="background-color: #e5f1ff; max-height: 300px; padding: 100px;">
    <div class="col">
      <h1 class="mb-3 fw-bold">Book Technician</h1>
      <h5>We consider all customers equal and generate a professional outcome of our work.</h5>
      <div class="d-flex justify-content-center mt-4">
        <form style="width: 60%;" action='{% url "search" %}' method='GET'>
          <div class="d-flex gap-3">
            <input type="text" name="s_type" class="form-control border border-dark rounded p-2" placeholder="Service Type">
            <input type="text" name='address' class="form-control border border-dark rounded p-2" placeholder="Location..." required id='id_address'>
            <input type="hidden" name='lat' value='' id='id_latitude'>
            <input type="hidden" name='lng' value='' id='id_longitude'>
            <select name="radius" id="radius" class='border border-dark rounded' required>
              <option value="" selected>Choose Radius</option>
              <option value="5" >5Km</option>
              <option value="10" >10Km</option>
              <option value="15" >15Km</option>
              <option value="25" >25Km</option>
            </select>
            <input type='submit' value='Search' class='btn btn-primary fw-bold py-2 rounded border-0 f-light' style='background-color:#070441;'>
          </div>       
        </form>
      </div>
    </div>
  </div>
</div>

<!-- text -->
<div class="container mb-3 mt-4">
  <div class="row">
    <div class="col-sm-6">  
      <p>- Look for your desire</p>
          <h3 class="fw-bold">Discover what makes us
            <br>top choice.</h3>
        </div>
      </div>
    </div>
    

<!-- technicians card -->

<div class="container mb-5">
  <div class="row justify-content-evenly px-2 g-1">
    {% for technician in page_obj %}
    {% if technician.is_available_status == True and technician.is_approved == True  %}
    {% comment %} {% if technician.is_approved == True  %} {% endcomment %}
    <div class="col-sm-3 position-relative mt-5 me-1 border border-dark rounded min-height-200 p-0 shadow-lg">
      <div class="card">
        <div class="d-flex gap-0 align-items-start">
          <img src="{{ technician.user.profile_picture.url }}" alt="" class="card-img-top rounded-circle" style="width: 75px; height: 75px;">
          {% if technician.user_profile.city == None %}
          <h6 class="card-text"></h6>
          {% else %}
          <h6 class="fw-bold card-text p-1 rounded mt-5 mx-1" style="background-color: rgba(247, 81, 81, 0.419);">{{technician.user_profile.city}}</h6>
          
          {% endif %}
          {% if technician.is_available_status == True and technician.is_booked_status == False %}
          <h6 class="fw-bold card-text p-1 rounded mt-5 mx-1" style="background-color: rgba(247, 81, 81, 0.419);"><i class="fa-solid fa-user-check"></i></h6>
          {% elif technician.is_booked_status == True %}
          <h6 class="fw-bold card-text p-1 rounded mt-5 mx-1" style="background-color: rgba(247, 81, 81, 0.419);"><i class="fa-solid fa-user-xmark"></i></h6>
          {% endif %}
          {% if address %}
            <h6 class="fw-bold card-text p-1 rounded mt-5 mx-1" style="background-color: rgba(247, 81, 81, 0.419);">
            <small>{{ technician.kms }}km</small>
            </h6>
          {% endif %}
        </div>
        
        <div class="card-body d-flex flex-column align-items-start mt-3">
          <h6 class="fw-bold card-text p-1 rounded" style="background-color: #E6E6FA;">{{ technician.user.first_name }} {{ technician.user.last_name }}</h6>
          <h6 class="fw-bold card-text p-1 rounded" style="background-color: #b2d4ab;">{{ technician.service_type }}</h6>
          {% comment %} <h6 class="fw-bold card-text p-1 rounded" style="background-color: #835aec;">{{ technician.service_type }}</h6> {% endcomment %}
          <p class="card-text mt-2">{{ technician.technician_description }}</p>
        </div>
      </div>
      <div class="mt-auto bottom-0 position-absolute w-100">
        {% if technician.is_booked_status == False %}
        <a href="{% url "bookNow" technician.id %}" class="btn btn-primary btn-block fw-bold w-100 p-2 fs-5 rounded border-0" style='background-color:#070441;'>Book Now</a>
        {% else %}
        <button onclick="showAlert()" class="btn btn-danger btn-block fw-bold w-100 p-2 fs-5 rounded border-0">Already Booked</button>
        {% endif %}
        <div class="alert alert-success show-notification" id="alertMessage" role="alert" style="display: none;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          This technician is already booked
         </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
</div>

<!-- Pagination -->
<div class="container">
  <nav aria-label="Page navigation">
      <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
    <li class="page-item m-1 border border-dark">
        <a class="page-link bg-secondary" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-label="Previous">
            <span aria-hidden="true" class='text-light fs-5 fw-bold'>&lt;</span>
        </a>
    </li>
{% endif %}
{% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
        <li class="page-item m-1 border border-dark active">
            <span class="page-link text-dark fs-5 fw-bold">{{ num }}</span>
        </li>
    {% else %}
        <li class="page-item m-1 border border-dark">
            <a class="page-link text-dark fs-5 fw-bold" href="?page={{ num }}">{{ num }}</a>
        </li>
    {% endif %}
{% endfor %}
{% if page_obj.has_next %}
    <li class="page-item m-1 border border-dark">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true" class='text-dark fs-5 fw-bold'>&gt;</span>
        </a>
    </li>
{% endif %}

    
      </ul>
  </nav>
</div>


<!-- Steps -->
<div class="container-fluid" style='background-color: #e5f1ff; height: 400px;'>
<div class="row justify-content-evenly">
  <h1 class='text-center mt-5 fw-bold mb-4'>Hire Technician</h1>
  <div class="col-md-3 d-flex flex-column align-items-center">
    <div class='m-3 rounded' style='background-color: #afe3c5; height: 80px; width: 80px;'>
      <h1 class='text-center pt-3'>1</h1>
    </div>
    <h4 class='fw-bold text-center'>Select Technician
      with service type</h4>
  </div>
  <div class="col-md-3 d-flex flex-column align-items-center">
    <div class='m-3 rounded' style='background-color: #afe3c5; height: 80px; width: 80px;'>
      <h1 class='text-center pt-3'>2</h1>
    </div>
    <h4 class='fw-bold text-center'>Select Prefered Time
      Slot</h4>
  </div>
  <div class="col-md-3 d-flex flex-column align-items-center">
    <div class='m-3 rounded' style='background-color: #afe3c5; height: 80px; width: 80px;'>
      <h1 class='text-center pt-3'>3</h1>
    </div>
    <h4 class='fw-bold text-center'>Book Technician</h4>
  </div>
</div>
</div>


<script>
  function showAlert() {
      // Show the alert
      document.getElementById("alertMessage").style.display = "block";
      setTimeout(function() {
        location.reload();
      }, 3500);
    
  }
</script>


	<!-- Footer -->

{% endblock  %}

templates/booking/cancel.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h3>Sorry!! Please try again</h3>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}